//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public byte[] VersionNumber { get; set; }
        public string MimeType { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public System.Guid AttachmentId { get; set; }
        public Nullable<int> UploadedToAWS { get; set; }
    }
}
