//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringEvent
    {
        public System.Guid CateringEventID { get; set; }
        public string EventName { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> Customer { get; set; }
        public Nullable<System.Guid> BookingContact { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> GuestsEstimated { get; set; }
        public Nullable<int> GuestsActual { get; set; }
        public Nullable<System.Guid> EventType { get; set; }
        public Nullable<System.Guid> Source { get; set; }
        public Nullable<System.Guid> CateringRep { get; set; }
        public Nullable<System.Guid> Location { get; set; }
        public Nullable<System.Guid> Site { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.Guid> Room { get; set; }
        public Nullable<System.Guid> SiteContact { get; set; }
        public string Description { get; set; }
        public string EventManagerNotes { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalGratuity { get; set; }
        public Nullable<decimal> TotalServiceCharge { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public Nullable<decimal> TotalFood { get; set; }
        public Nullable<decimal> TotalBeverage { get; set; }
        public Nullable<decimal> TotalLiquor { get; set; }
        public Nullable<decimal> TotalEquipment { get; set; }
        public Nullable<decimal> TotalLabor { get; set; }
        public Nullable<decimal> TotalVenue { get; set; }
        public Nullable<decimal> TotalDelivery { get; set; }
        public Nullable<decimal> TotalOther { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> TotalPerGuest { get; set; }
        public Nullable<decimal> TotalRemaining { get; set; }
        public Nullable<System.Guid> ItemTypeTemplate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> DateProspect { get; set; }
        public Nullable<System.DateTime> DateProposal { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public Nullable<System.DateTime> DateEventComplete { get; set; }
        public Nullable<System.DateTime> DateBillingComlete { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string CancelReason { get; set; }
        public Nullable<decimal> FoodCommission { get; set; }
        public Nullable<decimal> BeverageCommission { get; set; }
        public Nullable<decimal> LiquorCommission { get; set; }
        public Nullable<decimal> EquipmentCommission { get; set; }
        public Nullable<decimal> LaborCommission { get; set; }
        public Nullable<decimal> VenueCommission { get; set; }
        public Nullable<decimal> DeliveryCommission { get; set; }
        public Nullable<decimal> OtherCommission { get; set; }
        public string Country { get; set; }
    }
}
