//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringItemType
    {
        public System.Guid CateringItemTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> FoodTax { get; set; }
        public Nullable<decimal> FoodGratuity { get; set; }
        public Nullable<decimal> FoodServiceCharge { get; set; }
        public Nullable<System.Guid> FoodAccount { get; set; }
        public Nullable<decimal> BeverageTax { get; set; }
        public Nullable<decimal> BeverageGratuity { get; set; }
        public Nullable<decimal> BeverageServiceCharge { get; set; }
        public Nullable<System.Guid> BeverageAccount { get; set; }
        public Nullable<decimal> LiquorTax { get; set; }
        public Nullable<decimal> LiquorGratuity { get; set; }
        public Nullable<decimal> LiquorServiceCharge { get; set; }
        public Nullable<System.Guid> LiquorAccount { get; set; }
        public Nullable<decimal> EquipmentTax { get; set; }
        public Nullable<decimal> EquipmentGratuity { get; set; }
        public Nullable<decimal> EquipmentServiceCharge { get; set; }
        public Nullable<System.Guid> EquipmentAccount { get; set; }
        public Nullable<decimal> LaborTax { get; set; }
        public Nullable<decimal> LaborGratuity { get; set; }
        public Nullable<decimal> LaborServiceCharge { get; set; }
        public Nullable<System.Guid> LaborAccount { get; set; }
        public Nullable<decimal> VenueTax { get; set; }
        public Nullable<decimal> VenueGratuity { get; set; }
        public Nullable<decimal> VenueServiceCharge { get; set; }
        public Nullable<System.Guid> VenueAccount { get; set; }
        public Nullable<decimal> DeliveryTax { get; set; }
        public Nullable<decimal> DeliveryGratuity { get; set; }
        public Nullable<decimal> DeliveryServiceCharge { get; set; }
        public Nullable<System.Guid> DeliveryAccount { get; set; }
        public Nullable<decimal> OtherTax { get; set; }
        public Nullable<decimal> OtherGratuity { get; set; }
        public Nullable<decimal> OtherServiceCharge { get; set; }
        public Nullable<System.Guid> OtherAccount { get; set; }
        public Nullable<System.Guid> TaxAccount { get; set; }
        public Nullable<System.Guid> GratuityAccount { get; set; }
        public Nullable<System.Guid> ServiceChargeAccount { get; set; }
        public Nullable<bool> GratuityTaxable { get; set; }
        public Nullable<bool> ServiceChargeTaxable { get; set; }
        public Nullable<int> Custom { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
