//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactExtB
    {
        public System.Guid ContactId { get; set; }
        public Nullable<bool> dm_AllowTextMessaging { get; set; }
        public Nullable<int> dm_AnniversaryDay { get; set; }
        public Nullable<int> dm_AnniversaryMonth { get; set; }
        public Nullable<int> dm_BirthdayDay { get; set; }
        public Nullable<int> dm_BirthdayMonth { get; set; }
        public Nullable<bool> dm_EmailConfirmed { get; set; }
        public Nullable<int> dm_EmailFormat { get; set; }
        public Nullable<System.DateTime> dm_EmailSubscribeDate { get; set; }
        public string dm_imageattachmentid { get; set; }
        public string dm_IPAddress { get; set; }
        public Nullable<System.Guid> dm_FranchiseeId { get; set; }
    }
}
