//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controller
    {
        public string Batch { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public Nullable<int> JobCount { get; set; }
        public Nullable<int> EmployeeJobCount { get; set; }
        public Nullable<int> LaborCount { get; set; }
        public Nullable<int> SalesDetailCount { get; set; }
        public Nullable<int> SalesPaymentCount { get; set; }
        public Nullable<int> SalesCount { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<bool> UploadVerified { get; set; }
        public string DSSId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<bool> TransferVerified { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> TransferStartTime { get; set; }
    }
}
