//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public string Batch { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comment { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> Deposit2 { get; set; }
        public Nullable<decimal> Deposit3 { get; set; }
    }
}
