//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_attribute2extensionbase
    {
        public System.Guid dm_attribute2Id { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_LinkAllAttribute1 { get; set; }
        public Nullable<bool> dm_LinkAllAttribute3 { get; set; }
        public string dm_Number { get; set; }
        public Nullable<System.Guid> dm_AttributeSetup { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_PreferencesId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
