//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_autoidextensionbase
    {
        public System.Guid dm_autoidId { get; set; }
        public string dm_entityname { get; set; }
        public string dm_EntityIDFieldName { get; set; }
        public Nullable<int> dm_Lenght { get; set; }
        public Nullable<int> dm_NextID { get; set; }
        public string dm_Prefix { get; set; }
        public Nullable<int> dm_Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
