//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_bankRulesextensionbase
    {
        public System.Guid dm_BankRuleId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_Type { get; set; }
        public Nullable<System.Guid> dm_BankAccount { get; set; }
        public Nullable<int> dm_Condition { get; set; }
        public string dm_Value { get; set; }
        public Nullable<System.Guid> dm_Vendor { get; set; }
        public Nullable<System.Guid> dm_Account { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<int> dm_Condition2 { get; set; }
        public string dm_Value2 { get; set; }
    }
}
