//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_bankActivity
    {
        public System.Guid dm_bankactivityId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_ActivityStatus { get; set; }
        public string dm_ActivityType { get; set; }
        public Nullable<decimal> dm_Amount { get; set; }
        public Nullable<decimal> dm_amount_Base { get; set; }
        public string dm_banktransactionid { get; set; }
        public string dm_blank { get; set; }
        public string dm_CheckNumber { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_Memo { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_BankAccount { get; set; }
        public Nullable<System.Guid> dm_Locations { get; set; }
        public Nullable<System.Guid> dm_CreateTransaction { get; set; }
        public Nullable<System.Guid> dm_LinkedTransaction { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
