//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_bankRecDetail
    {
        public System.Guid dm_bankrecdetailId { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_Cleared { get; set; }
        public string dm_CompanyText { get; set; }
        public Nullable<decimal> dm_Credit { get; set; }
        public Nullable<decimal> dm_credit_Base { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public Nullable<decimal> dm_Debit { get; set; }
        public Nullable<decimal> dm_debit_Base { get; set; }
        public string dm_Number { get; set; }
        public Nullable<int> dm_TransactionType { get; set; }
        public Nullable<System.Guid> dm_Reconciliation { get; set; }
        public Nullable<System.Guid> dm_CheckingAccount { get; set; }
        public Nullable<System.Guid> dm_Transaction { get; set; }
        public Nullable<System.Guid> dm_TransactionDetail { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
