//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_bankextensionbase
    {
        public System.Guid dm_bankId { get; set; }
        public string dm_name { get; set; }
        public string dm_ACHReport { get; set; }
        public Nullable<int> dm_Application { get; set; }
        public string dm_BankCode { get; set; }
        public string dm_FID { get; set; }
        public string dm_OFXURL { get; set; }
        public string dm_PositivePayReport { get; set; }
        public Nullable<bool> dm_UseBankCode { get; set; }
        public Nullable<int> dm_version { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
