//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_CheckRunInvoice
    {
        public System.Guid InvoiceDetailId { get; set; }
        public string checkRunId { get; set; }
        public Nullable<decimal> pay { get; set; }
        public Nullable<decimal> payAmount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string companyId { get; set; }
        public string company { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string invoice { get; set; }
        public string invoiceId { get; set; }
        public Nullable<decimal> creditExpected { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public Nullable<System.DateTime> discountDate { get; set; }
        public Nullable<decimal> discountPercent { get; set; }
        public Nullable<decimal> discountSuggested { get; set; }
        public string discountAccount { get; set; }
        public string discountAccountId { get; set; }
        public string location { get; set; }
        public string locationId { get; set; }
        public string paymentTerms { get; set; }
        public string paymentTermsId { get; set; }
        public string number { get; set; }
        public Nullable<decimal> amountRemaining { get; set; }
        public Nullable<decimal> appliedAmount { get; set; }
        public Nullable<bool> shortPay { get; set; }
        public string defaultCheckMemo { get; set; }
        public string transactionId { get; set; }
        public string creditAvailable { get; set; }
        public string discountAvailable { get; set; }
        public string version { get; set; }
        public Nullable<decimal> amountOriginal { get; set; }
        public Nullable<decimal> discountAmountOriginal { get; set; }
        public Nullable<decimal> amountRemainingOriginal { get; set; }
        public Nullable<decimal> appliedAmountOriginal { get; set; }
        public string vendorEmail { get; set; }
        public string toolTip { get; set; }
        public Nullable<bool> lineColor { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
