//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_cateringEventDetail
    {
        public System.Guid dm_cateringeventdetailId { get; set; }
        public string dm_name { get; set; }
        public Nullable<decimal> dm_Cost { get; set; }
        public Nullable<decimal> dm_cost_Base { get; set; }
        public string dm_Details { get; set; }
        public Nullable<decimal> dm_Hours { get; set; }
        public Nullable<decimal> dm_Price { get; set; }
        public Nullable<decimal> dm_price_Base { get; set; }
        public Nullable<decimal> dm_Qty { get; set; }
        public Nullable<decimal> dm_Total { get; set; }
        public Nullable<decimal> dm_total_Base { get; set; }
        public Nullable<decimal> dm_TotalCost { get; set; }
        public Nullable<decimal> dm_totalcost_Base { get; set; }
        public Nullable<System.Guid> dm_CateringItem { get; set; }
        public Nullable<System.Guid> dm_Employee { get; set; }
        public Nullable<System.Guid> dm_Item { get; set; }
        public Nullable<System.Guid> dm_CateringEvent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
