//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_dailySalesSummary
    {
        public System.Guid dm_dailysalessummaryId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_100Bills { get; set; }
        public Nullable<int> dm_10Bills { get; set; }
        public Nullable<int> dm_1Bills { get; set; }
        public Nullable<int> dm_20Bills { get; set; }
        public Nullable<int> dm_2Bills { get; set; }
        public Nullable<int> dm_50Bills { get; set; }
        public Nullable<int> dm_5Bills { get; set; }
        public string dm_AccountingComments { get; set; }
        public Nullable<int> dm_ApprovalStatus { get; set; }
        public Nullable<decimal> dm_AverageCheck { get; set; }
        public Nullable<decimal> dm_averagecheck_Base { get; set; }
        public Nullable<decimal> dm_AverageCheckPriorYear { get; set; }
        public Nullable<decimal> dm_averagecheckprioryear_Base { get; set; }
        public Nullable<decimal> dm_CashCheckCoin { get; set; }
        public Nullable<decimal> dm_cashcheckcoin_Base { get; set; }
        public Nullable<decimal> dm_CashPaymentAmount { get; set; }
        public Nullable<decimal> dm_cashpaymentamount_Base { get; set; }
        public Nullable<int> dm_CashPaymentCount { get; set; }
        public Nullable<int> dm_ClosingStatus { get; set; }
        public Nullable<decimal> dm_CompPaymentAmount { get; set; }
        public Nullable<decimal> dm_comppaymentamount_Base { get; set; }
        public Nullable<int> dm_CompPaymentCount { get; set; }
        public Nullable<decimal> dm_CouponPaymentAmount { get; set; }
        public Nullable<decimal> dm_couponpaymentamount_Base { get; set; }
        public Nullable<int> dm_CouponPaymentCount { get; set; }
        public Nullable<decimal> dm_CreditCardPaymentAmount { get; set; }
        public Nullable<decimal> dm_creditcardpaymentamount_Base { get; set; }
        public Nullable<int> dm_CreditCardPaymentCount { get; set; }
        public Nullable<System.DateTime> dm_CurrentYearDate { get; set; }
        public string dm_DailyComment { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_DateText { get; set; }
        public Nullable<int> dm_DayofWeek { get; set; }
        public string dm_DayPart1Comment { get; set; }
        public string dm_DayPart2Comment { get; set; }
        public string dm_DayPart3Comment { get; set; }
        public string dm_DayPart4Comment { get; set; }
        public string dm_DayPart5Comment { get; set; }
        public string dm_DayPart6Comment { get; set; }
        public Nullable<bool> dm_Deposited { get; set; }
        public string dm_dinnercondition { get; set; }
        public Nullable<int> dm_dinnertemperature { get; set; }
        public Nullable<decimal> dm_DiscountPaymentAmount { get; set; }
        public Nullable<decimal> dm_discountpaymentamount_Base { get; set; }
        public Nullable<int> dm_DiscountPaymentCount { get; set; }
        public Nullable<int> dm_DSSType { get; set; }
        public Nullable<decimal> dm_GiftcardPaymentAmount { get; set; }
        public Nullable<decimal> dm_giftcardpaymentamount_Base { get; set; }
        public Nullable<int> dm_GiftcardPaymentCount { get; set; }
        public Nullable<int> dm_GuestCount { get; set; }
        public Nullable<int> dm_GuestCountPriorYear { get; set; }
        public Nullable<decimal> dm_HouseAccountPaymentAmount { get; set; }
        public Nullable<decimal> dm_houseaccountpaymentamount_Base { get; set; }
        public Nullable<int> dm_HouseAccountPaymentCount { get; set; }
        public Nullable<bool> dm_importcomplete { get; set; }
        public Nullable<decimal> dm_JournalEntryAdjustment { get; set; }
        public Nullable<decimal> dm_journalentryadjustment_Base { get; set; }
        public Nullable<int> dm_LaborGoal { get; set; }
        public Nullable<decimal> dm_LaborOTAmount { get; set; }
        public Nullable<decimal> dm_laborotamount_Base { get; set; }
        public Nullable<decimal> dm_LaborOtherAmount { get; set; }
        public Nullable<decimal> dm_laborotheramount_Base { get; set; }
        public Nullable<decimal> dm_LaborOtherHrs { get; set; }
        public Nullable<decimal> dm_LaborOTHrs { get; set; }
        public Nullable<int> dm_Laborpercent { get; set; }
        public Nullable<decimal> dm_LaborRegularAmount { get; set; }
        public Nullable<decimal> dm_laborregularamount_Base { get; set; }
        public Nullable<decimal> dm_LaborRegularHrs { get; set; }
        public string dm_LastYearDinnerCondition { get; set; }
        public Nullable<int> dm_LastYearDinnerTemperature { get; set; }
        public string dm_LastYearLunchCondition { get; set; }
        public Nullable<int> dm_LastYearLunchTemperature { get; set; }
        public string dm_lunchcondition { get; set; }
        public Nullable<int> dm_lunchtemperature { get; set; }
        public Nullable<decimal> dm_NetSales { get; set; }
        public Nullable<decimal> dm_netsales_Base { get; set; }
        public Nullable<decimal> dm_NonCashTips { get; set; }
        public Nullable<decimal> dm_noncashtips_Base { get; set; }
        public Nullable<decimal> dm_OverShort { get; set; }
        public Nullable<decimal> dm_overshort_Base { get; set; }
        public Nullable<decimal> dm_PaidoutTotal { get; set; }
        public Nullable<decimal> dm_paidouttotal_Base { get; set; }
        public Nullable<bool> dm_PayrollApproved { get; set; }
        public Nullable<bool> dm_PayTipsWithPayroll { get; set; }
        public Nullable<decimal> dm_PettyCash { get; set; }
        public Nullable<decimal> dm_pettycash_Base { get; set; }
        public Nullable<bool> dm_PettyCashinDailyClose { get; set; }
        public Nullable<decimal> dm_PIAPaymentAmount { get; set; }
        public Nullable<decimal> dm_piapaymentamount_Base { get; set; }
        public Nullable<int> dm_PIAPaymentCount { get; set; }
        public Nullable<decimal> dm_POSCashCoinCheckTotal { get; set; }
        public Nullable<decimal> dm_poscashcoinchecktotal_Base { get; set; }
        public Nullable<decimal> dm_POSCashMinusPaidout { get; set; }
        public Nullable<decimal> dm_poscashminuspaidout_Base { get; set; }
        public string dm_R365OperationsImportVersion { get; set; }
        public string dm_ReviewComments { get; set; }
        public Nullable<decimal> dm_SalesPercentofLastYear { get; set; }
        public Nullable<decimal> dm_SameDayLastYearSales { get; set; }
        public Nullable<decimal> dm_samedaylastyearsales_Base { get; set; }
        public string dm_SaveAndCloseButton { get; set; }
        public string dm_SaveandNext { get; set; }
        public string dm_Step1CompleteButton { get; set; }
        public string dm_Step2CompleteButton { get; set; }
        public string dm_Step2NoInsertCompleteButton { get; set; }
        public string dm_Step3CompleteButton { get; set; }
        public Nullable<bool> dm_StepsComplete { get; set; }
        public Nullable<decimal> dm_TipsPaidWithPettyCash { get; set; }
        public Nullable<decimal> dm_tipspaidwithpettycash_Base { get; set; }
        public Nullable<decimal> dm_Total100Bills { get; set; }
        public Nullable<decimal> dm_total100bills_Base { get; set; }
        public Nullable<decimal> dm_Total10Bills { get; set; }
        public Nullable<decimal> dm_total10bills_Base { get; set; }
        public Nullable<decimal> dm_Total1Bills { get; set; }
        public Nullable<decimal> dm_total1bills_Base { get; set; }
        public Nullable<decimal> dm_Total20Bills { get; set; }
        public Nullable<decimal> dm_total20bills_Base { get; set; }
        public Nullable<decimal> dm_Total2Bills { get; set; }
        public Nullable<decimal> dm_total2bills_Base { get; set; }
        public Nullable<decimal> dm_Total50Bills { get; set; }
        public Nullable<decimal> dm_total50bills_Base { get; set; }
        public Nullable<decimal> dm_Total5Bills { get; set; }
        public Nullable<decimal> dm_total5bills_Base { get; set; }
        public Nullable<decimal> dm_TotalCash { get; set; }
        public Nullable<decimal> dm_totalcash_Base { get; set; }
        public Nullable<decimal> dm_TotalCashCoin { get; set; }
        public Nullable<decimal> dm_totalcashcoin_Base { get; set; }
        public Nullable<decimal> dm_TotalChecks { get; set; }
        public Nullable<decimal> dm_totalchecks_Base { get; set; }
        public Nullable<decimal> dm_TotalCoin { get; set; }
        public Nullable<decimal> dm_totalcoin_Base { get; set; }
        public Nullable<decimal> dm_TotalDeposit { get; set; }
        public Nullable<decimal> dm_totaldeposit_Base { get; set; }
        public Nullable<decimal> dm_TotalLabor { get; set; }
        public Nullable<decimal> dm_totallabor_Base { get; set; }
        public Nullable<decimal> dm_TotalNonCashTender { get; set; }
        public Nullable<decimal> dm_totalnoncashtender_Base { get; set; }
        public Nullable<decimal> dm_TotalSales { get; set; }
        public Nullable<decimal> dm_totalsales_Base { get; set; }
        public Nullable<decimal> dm_TotalTender { get; set; }
        public Nullable<decimal> dm_totaltender_Base { get; set; }
        public Nullable<decimal> dm_UnpaidCashTips { get; set; }
        public Nullable<decimal> dm_unpaidcashtips_Base { get; set; }
        public Nullable<decimal> dm_VoidPaymentAmount { get; set; }
        public Nullable<decimal> dm_voidpaymentamount_Base { get; set; }
        public Nullable<int> dm_VoidPaymentCount { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_ClosingEmployee { get; set; }
        public Nullable<System.Guid> dm_FiscalDate { get; set; }
        public Nullable<System.Guid> dm_JournalEntry { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<decimal> dm_DailyManagerSalary { get; set; }
        public Nullable<decimal> Deposit1 { get; set; }
        public Nullable<decimal> Deposit2 { get; set; }
        public Nullable<decimal> Deposit3 { get; set; }
    }
}
