//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_EmployeeNoteReasonextensionbase
    {
        public System.Guid dm_EmpolyeeNoteReasonsId { get; set; }
        public string dm_name { get; set; }
    }
}
