//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_employee
    {
        public System.Guid dm_employeeId { get; set; }
        public string dm_FullName { get; set; }
        public string dm_Address1 { get; set; }
        public string dm_Address2 { get; set; }
        public Nullable<bool> dm_AllowTextMessaging { get; set; }
        public Nullable<int> dm_BirthdayDay { get; set; }
        public Nullable<int> dm_BirthdayMonth { get; set; }
        public string dm_City { get; set; }
        public string dm_FirstName { get; set; }
        public Nullable<System.DateTime> dm_HireDate { get; set; }
        public string dm_imageattachmentid { get; set; }
        public string dm_LastName { get; set; }
        public string dm_MiddleName { get; set; }
        public string dm_MobilePhone { get; set; }
        public Nullable<int> dm_MultipleLocations { get; set; }
        public string dm_PayrollID { get; set; }
        public string dm_PhoneNumber { get; set; }
        public string dm_POSID { get; set; }
        public string dm_SSNumber { get; set; }
        public string dm_State { get; set; }
        public string dm_ZipCode { get; set; }
        public Nullable<System.Guid> dm_EmployeeLink { get; set; }
        public Nullable<System.Guid> dm_PrimaryLocation { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> dm_BreakWaiver { get; set; }
        public Nullable<int> dm_PreferredContactMethod { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> changepassword { get; set; }
        public Nullable<bool> AppAccess { get; set; }
    }
}
