//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_employeeAvailability
    {
        public string Id { get; set; }
        public System.Guid dm_employeeId { get; set; }
        public int dm_day { get; set; }
        public Nullable<bool> dm_unavailableAllDay { get; set; }
        public Nullable<bool> dm_availableAllDay { get; set; }
        public Nullable<System.DateTime> dm_start { get; set; }
        public Nullable<System.DateTime> dm_end { get; set; }
    }
}
