//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_franchiseeextensionbase
    {
        public System.Guid dm_franchiseeId { get; set; }
        public string dm_name { get; set; }
        public string dm_AreaDetails { get; set; }
        public string dm_FranchiseeTermComments { get; set; }
        public string dm_Region { get; set; }
        public Nullable<System.DateTime> dm_TermExpiration { get; set; }
        public string dm_Terms { get; set; }
        public Nullable<System.DateTime> dm_TermStart { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> BillingOption { get; set; }
        public string BillingCustomer { get; set; }
    }
}
