//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_franchiseeLocation
    {
        public System.Guid dm_franchiseelocationId { get; set; }
        public string dm_name { get; set; }
        public Nullable<decimal> dm_AdvertisingPercentage { get; set; }
        public string dm_City { get; set; }
        public string dm_Country { get; set; }
        public Nullable<System.DateTime> dm_DateOpened { get; set; }
        public string dm_Phone { get; set; }
        public Nullable<decimal> dm_RoyaltyPercentage { get; set; }
        public string dm_State { get; set; }
        public string dm_Street1 { get; set; }
        public string dm_Street2 { get; set; }
        public Nullable<decimal> dm_YesterdayAvgCheck { get; set; }
        public Nullable<decimal> dm_yesterdayavgcheck_Base { get; set; }
        public Nullable<int> dm_YesterdayGuests { get; set; }
        public Nullable<decimal> dm_YesterdaySales { get; set; }
        public Nullable<decimal> dm_yesterdaysales_Base { get; set; }
        public string dm_ZipCode { get; set; }
        public Nullable<System.Guid> dm_CompanyEntityId { get; set; }
        public Nullable<System.Guid> dm_PrimaryContactId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
