//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_franchiseeReviews
    {
        public System.Guid dm_franchiseereviewsId { get; set; }
        public string dm_name { get; set; }
        public string dm_Comment { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_Description { get; set; }
        public string dm_Frequency { get; set; }
        public Nullable<bool> dm_Pass { get; set; }
        public Nullable<decimal> dm_Score { get; set; }
        public Nullable<System.Guid> dm_Store { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
