//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_fiscalDate
    {
        public System.Guid dm_fiscaldateId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_CalendarDay { get; set; }
        public Nullable<int> dm_CalendarMonth { get; set; }
        public string dm_CalendarYear { get; set; }
        public Nullable<int> dm_CombinedReportingDay { get; set; }
        public string dm_CombinedReportingDayYear { get; set; }
        public Nullable<int> dm_CombinedReportingPeriod { get; set; }
        public string dm_CombinedReportingPeriodName { get; set; }
        public string dm_CombinedReportingPeriodYear { get; set; }
        public Nullable<int> dm_CombinedReportingQuarter { get; set; }
        public string dm_CombinedReportingQuarterYear { get; set; }
        public Nullable<int> dm_CombinedReportingWeek { get; set; }
        public string dm_CombinedReportingWeekYear { get; set; }
        public string dm_CombinedReportingYear1 { get; set; }
        public Nullable<System.DateTime> dm_CurrentDate { get; set; }
        public Nullable<int> dm_CurrentDaysBack { get; set; }
        public Nullable<bool> dm_CurrentOrPriorYear { get; set; }
        public Nullable<int> dm_CurrentPeriodsBack { get; set; }
        public Nullable<int> dm_CurrentQuartersBack { get; set; }
        public Nullable<int> dm_CurrentWeeksBack { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_DateText { get; set; }
        public Nullable<int> dm_DayName { get; set; }
        public Nullable<int> dm_DaysBack { get; set; }
        public Nullable<int> dm_FiscalDateType { get; set; }
        public Nullable<int> dm_FiscalDay { get; set; }
        public string dm_FiscalDayYear { get; set; }
        public Nullable<int> dm_FiscalPeriod { get; set; }
        public string dm_FiscalPeriodYear { get; set; }
        public Nullable<int> dm_FiscalQuarter { get; set; }
        public string dm_FiscalQuarterYear { get; set; }
        public Nullable<int> dm_FiscalWeek { get; set; }
        public string dm_FiscalWeekYear { get; set; }
        public string dm_FiscalYear1 { get; set; }
        public string dm_LastYearDinnerCondition { get; set; }
        public Nullable<int> dm_LastYearDinnerTemperature { get; set; }
        public string dm_lastyearlunchcondition { get; set; }
        public Nullable<int> dm_LastYearLunchTemperature { get; set; }
        public string dm_PeriodName { get; set; }
        public Nullable<int> dm_PeriodsBack { get; set; }
        public Nullable<int> dm_QuartersBack { get; set; }
        public string dm_WeekName { get; set; }
        public Nullable<int> dm_WeeksBack { get; set; }
        public Nullable<int> dm_YearsBack { get; set; }
        public Nullable<System.Guid> dm_FiscalPeriodSetup { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
