//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_fiscalPeriodSetupextensionbase
    {
        public System.Guid dm_fiscalperiodsetupId { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_BrandNew { get; set; }
        public Nullable<System.DateTime> dm_EndDate { get; set; }
        public Nullable<int> dm_FirstDayofWeek { get; set; }
        public Nullable<bool> dm_FiscalOperationalYear { get; set; }
        public Nullable<System.DateTime> dm_OperationalYearEndDate { get; set; }
        public Nullable<System.DateTime> dm_OperationalYearStartDate { get; set; }
        public Nullable<int> dm_OperationYearFirstDayofWeek { get; set; }
        public Nullable<int> dm_OperationYearPeriodStructure { get; set; }
        public Nullable<int> dm_PeriodStructure { get; set; }
        public Nullable<System.DateTime> dm_StartDate { get; set; }
        public Nullable<int> dm_Year { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
