//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_item
    {
        public System.Guid dm_itemId { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_Active { get; set; }
        public Nullable<bool> dm_AvailableAllLocations { get; set; }
        public Nullable<bool> dm_AvailabletoSell { get; set; }
        public string dm_Brand { get; set; }
        public Nullable<bool> dm_CateringItem { get; set; }
        public Nullable<decimal> dm_CookMinutes { get; set; }
        public Nullable<decimal> dm_Cost { get; set; }
        public Nullable<decimal> dm_cost_Base { get; set; }
        public Nullable<int> dm_CostUpdate { get; set; }
        public string dm_Description { get; set; }
        public Nullable<bool> dm_EachActive { get; set; }
        public Nullable<decimal> dm_EachBaseQty { get; set; }
        public Nullable<decimal> dm_EquivalenceEachQty { get; set; }
        public Nullable<decimal> dm_EquivalenceVolumeQty { get; set; }
        public Nullable<decimal> dm_EquivalenceWeightQty { get; set; }
        public Nullable<decimal> dm_FinishMinutes { get; set; }
        public Nullable<bool> dm_IncludeInCount { get; set; }
        public Nullable<bool> dm_KeyItem { get; set; }
        public string dm_LongDescription { get; set; }
        public string dm_Number { get; set; }
        public Nullable<decimal> dm_NumberofPortions { get; set; }
        public Nullable<decimal> dm_ParQty { get; set; }
        public Nullable<decimal> dm_PortionSize { get; set; }
        public Nullable<decimal> dm_PrepMinutes { get; set; }
        public Nullable<decimal> dm_Price { get; set; }
        public Nullable<decimal> dm_price_Base { get; set; }
        public Nullable<int> dm_PrimaryUofMType { get; set; }
        public string dm_PurchaseUofM { get; set; }
        public string dm_ServingPlate { get; set; }
        public Nullable<decimal> dm_ShelfLifeDays { get; set; }
        public string dm_Steps { get; set; }
        public string dm_StockCountUofM { get; set; }
        public string dm_StorageContainer { get; set; }
        public Nullable<bool> dm_Taxable { get; set; }
        public string dm_Tools { get; set; }
        public Nullable<int> dm_Type { get; set; }
        public Nullable<bool> dm_VolumeActive { get; set; }
        public Nullable<decimal> dm_VolumeBaseQty { get; set; }
        public Nullable<bool> dm_WeightActive { get; set; }
        public Nullable<decimal> dm_WeightBaseQty { get; set; }
        public Nullable<decimal> dm_YieldPercent { get; set; }
        public Nullable<decimal> dm_YieldQty { get; set; }
        public Nullable<System.Guid> dm_CateringCategory { get; set; }
        public Nullable<System.Guid> dm_CostAccount { get; set; }
        public Nullable<System.Guid> dm_InventoryAccount { get; set; }
        public Nullable<System.Guid> dm_SalesAccount { get; set; }
        public Nullable<System.Guid> dm_WasteAccount { get; set; }
        public Nullable<System.Guid> dm_ItemCategory1 { get; set; }
        public Nullable<System.Guid> dm_ItemCategory2 { get; set; }
        public Nullable<System.Guid> dm_ItemCategory3 { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_EachBaseUofM { get; set; }
        public Nullable<System.Guid> dm_EquivalenceEachUofM { get; set; }
        public Nullable<System.Guid> dm_EquivalenceVolumeUofM { get; set; }
        public Nullable<System.Guid> dm_EquivalenceWeightUofM { get; set; }
        public Nullable<System.Guid> dm_InventoryUofM { get; set; }
        public Nullable<System.Guid> dm_PortionUofM { get; set; }
        public Nullable<System.Guid> dm_PurchasingUofM { get; set; }
        public Nullable<System.Guid> dm_SalesUofM { get; set; }
        public Nullable<System.Guid> dm_VolumeBaseUofM { get; set; }
        public Nullable<System.Guid> dm_WeightBaseUofM { get; set; }
        public Nullable<System.Guid> dm_YieldUofM { get; set; }
        public Nullable<bool> dm_AvailableInInventory { get; set; }
        public Nullable<int> dm_RecipeCostUpdate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> CommissaryItem { get; set; }
        public Nullable<System.Guid> CommissaryCategory { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CateringType { get; set; }
        public Nullable<System.Guid> CateringCategory { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> ServiceChgExempt { get; set; }
        public Nullable<bool> GratuityExempt { get; set; }
        public string CateringDescription { get; set; }
        public Nullable<decimal> AcceptableTheoreticalVariance { get; set; }
        public Nullable<System.Guid> CountUofM2 { get; set; }
        public Nullable<System.Guid> CountUofM3 { get; set; }
    }
}
