//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_ingredientextensionbase
    {
        public System.Guid dm_ingredientId { get; set; }
        public string dm_name { get; set; }
        public string dm_Instructions { get; set; }
        public Nullable<decimal> dm_Qty { get; set; }
        public Nullable<decimal> dm_YieldPercent { get; set; }
        public Nullable<System.Guid> dm_Item { get; set; }
        public Nullable<System.Guid> dm_Recipe { get; set; }
        public Nullable<System.Guid> dm_UofM { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> IngredientSort { get; set; }
    }
}
