//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_locationextensionbase
    {
        public System.Guid dm_locationId { get; set; }
        public string dm_name { get; set; }
        public string dm_City { get; set; }
        public Nullable<decimal> dm_DailyManagerSalary { get; set; }
        public Nullable<decimal> dm_dailymanagersalary_Base { get; set; }
        public string dm_DayPart1Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart1StartTime { get; set; }
        public string dm_DayPart2Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart2StartTime { get; set; }
        public string dm_DayPart3Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart3StartTime { get; set; }
        public string dm_DayPart4Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart4StartTime { get; set; }
        public string dm_DayPart5Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart5StartTime { get; set; }
        public string dm_DayPart6Name { get; set; }
        public Nullable<System.DateTime> dm_DayPart6StartTime { get; set; }
        public Nullable<bool> dm_DepositOnFriday { get; set; }
        public Nullable<bool> dm_DepositOnMonday { get; set; }
        public Nullable<bool> dm_DepositOnSaturday { get; set; }
        public Nullable<bool> dm_DepositOnSunday { get; set; }
        public Nullable<bool> dm_DepositOnThursday { get; set; }
        public Nullable<bool> dm_DepositOnTuesday { get; set; }
        public Nullable<bool> dm_DepositOnWednesday { get; set; }
        public Nullable<bool> dm_ExcludeFromDashboard { get; set; }
        public string dm_Fax { get; set; }
        public Nullable<bool> dm_FinancialStatusBasedOn { get; set; }
        public Nullable<decimal> dm_LaborGoal { get; set; }
        public string dm_LocationNumber { get; set; }
        public Nullable<System.DateTime> dm_MostRecentCloseDate { get; set; }
        public Nullable<int> dm_mtc_financialstatus { get; set; }
        public Nullable<decimal> dm_PayrollBenefitEstimate { get; set; }
        public Nullable<decimal> dm_PayrollOtherEstimate { get; set; }
        public Nullable<decimal> dm_PayrollTaxEstimate { get; set; }
        public string dm_Phone1 { get; set; }
        public string dm_Phone2 { get; set; }
        public Nullable<int> dm_PreviousDayLabor { get; set; }
        public Nullable<decimal> dm_PreviousDayLaborTotal { get; set; }
        public Nullable<decimal> dm_previousdaylabortotal_Base { get; set; }
        public Nullable<decimal> dm_PreviousDaySales { get; set; }
        public Nullable<decimal> dm_previousdaysales_Base { get; set; }
        public Nullable<decimal> dm_PreviousDaySalesofLastYear { get; set; }
        public Nullable<decimal> dm_SalesIncreaseGoal { get; set; }
        public Nullable<int> dm_SalesPercentofLastYear { get; set; }
        public Nullable<decimal> dm_SalesTaxRate { get; set; }
        public Nullable<decimal> dm_SameDayLastYearSales { get; set; }
        public Nullable<decimal> dm_samedaylastyearsales_Base { get; set; }
        public Nullable<int> dm_SQFT { get; set; }
        public Nullable<System.DateTime> dm_StartDate { get; set; }
        public string dm_State { get; set; }
        public string dm_Street1 { get; set; }
        public string dm_Street2 { get; set; }
        public Nullable<bool> dm_WeeklyJournalEntry { get; set; }
        public string dm_Zip { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_Concept { get; set; }
        public Nullable<System.Guid> dm_ClosingEmployee { get; set; }
        public Nullable<System.Guid> dm_DefaultCateringChef { get; set; }
        public Nullable<System.Guid> dm_LocationManager { get; set; }
        public Nullable<System.Guid> dm_APAccount { get; set; }
        public Nullable<System.Guid> dm_CashAccount { get; set; }
        public Nullable<System.Guid> dm_CashOffsetAccount { get; set; }
        public Nullable<System.Guid> dm_CreditExpectedAccount { get; set; }
        public Nullable<System.Guid> dm_ManagerPayrollAccount { get; set; }
        public Nullable<System.Guid> dm_OverShortAccount { get; set; }
        public Nullable<System.Guid> dm_PayrollBenefitEstimateAccount { get; set; }
        public Nullable<System.Guid> dm_PayrollEstimateOffsetAccount { get; set; }
        public Nullable<System.Guid> dm_PayrollOtherEstimateAccount { get; set; }
        public Nullable<System.Guid> dm_PayrollTaxEstimateAccount { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.DateTime> dm_ClosingTime { get; set; }
        public Nullable<bool> dm_PayTipsWithPayroll { get; set; }
        public Nullable<System.Guid> dm_TipsPayableAccount { get; set; }
        public Nullable<bool> dm_PettyCashInDailyClose { get; set; }
        public Nullable<System.Guid> dm_PettyCashAccount { get; set; }
        public string dm_CateringName { get; set; }
        public Nullable<int> dm_DayPartStartTime1 { get; set; }
        public Nullable<int> dm_DayPartStartTime2 { get; set; }
        public Nullable<int> dm_DayPartStartTime3 { get; set; }
        public Nullable<int> dm_DayPartStartTime4 { get; set; }
        public Nullable<int> dm_DayPartStartTime5 { get; set; }
        public Nullable<int> dm_DayPartStartTime6 { get; set; }
        public Nullable<int> dm_CloseTime { get; set; }
        public Nullable<decimal> dm_NetSalesGoalMonday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalTuesday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalWednesday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalThursday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalFriday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalSaturday { get; set; }
        public Nullable<decimal> dm_NetSalesGoalSunday { get; set; }
        public Nullable<decimal> dm_DayPart1AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DayPart2AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DayPart3AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DayPart4AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DayPart5AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DayPart6AvgCheckGoal { get; set; }
        public Nullable<decimal> dm_DailyTargetAvgCheck { get; set; }
        public Nullable<int> dm_OvertimeTracking { get; set; }
        public Nullable<bool> dm_AutoImport { get; set; }
        public Nullable<int> dm_ImportDaysBack { get; set; }
        public Nullable<System.Guid> dm_DefaultBudget { get; set; }
        public Nullable<decimal> dm_LaborGoalSunday { get; set; }
        public Nullable<decimal> dm_LaborGoalMonday { get; set; }
        public Nullable<decimal> dm_LaborGoalWednesday { get; set; }
        public Nullable<decimal> dm_LaborGoalThursday { get; set; }
        public Nullable<decimal> dm_LaborGoalFriday { get; set; }
        public Nullable<decimal> dm_LaborGoalSaturday { get; set; }
        public Nullable<decimal> dm_LaborGoalTuesday { get; set; }
        public Nullable<int> dm_POSImportType { get; set; }
        public string dm_POSSystem { get; set; }
        public Nullable<System.DateTime> dm_POSImportStart { get; set; }
        public Nullable<System.DateTime> dm_CompStartDate { get; set; }
        public Nullable<System.DateTime> dm_CompEndDate { get; set; }
        public Nullable<int> dm_BreakAfterNoWaiver { get; set; }
        public Nullable<int> dm_BreakAfterWaiver { get; set; }
        public Nullable<int> dm_BreakMinutes { get; set; }
        public Nullable<int> dm_BreakPenaltyMinutes { get; set; }
        public string dm_BreakPenaltyRate { get; set; }
        public Nullable<decimal> dm_MinimumWage { get; set; }
        public Nullable<int> dm_BreakPenaltiesPerDay { get; set; }
        public Nullable<int> dm_SplitMinutes { get; set; }
        public Nullable<int> dm_SplitPenaltyMinutes { get; set; }
        public string dm_SplitPenaltyRate { get; set; }
        public Nullable<System.Guid> LocationCategory1 { get; set; }
        public Nullable<System.Guid> LocationCategory2 { get; set; }
        public Nullable<System.Guid> LocationCategory3 { get; set; }
        public Nullable<System.Guid> LocationCategory4 { get; set; }
        public Nullable<System.Guid> LocationCategory5 { get; set; }
        public Nullable<System.Guid> LocationCategory6 { get; set; }
        public Nullable<System.Guid> LocationCategory7 { get; set; }
        public Nullable<System.Guid> LocationCategory8 { get; set; }
        public Nullable<System.Guid> LocationCategory9 { get; set; }
        public Nullable<System.Guid> LocationCategory10 { get; set; }
        public Nullable<System.Guid> CateringItemTypeTemplate { get; set; }
        public Nullable<System.Guid> CommissaryLocation { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> dm_SecondShiftMinimumMinutes { get; set; }
        public string FTPFolderName { get; set; }
        public Nullable<decimal> AdditionalInfoNumber1 { get; set; }
        public Nullable<decimal> AdditionalInfoNumber2 { get; set; }
        public Nullable<decimal> AdditionalInfoNumber3 { get; set; }
        public string AdditionalInfoText1 { get; set; }
        public string AdditionalInfoText2 { get; set; }
        public Nullable<System.Guid> POSGroup { get; set; }
        public Nullable<System.Guid> FoodType { get; set; }
        public Nullable<System.Guid> LocationType { get; set; }
        public Nullable<System.Guid> POSSystem { get; set; }
    }
}
