//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_legalEntity
    {
        public System.Guid dm_legalentityId { get; set; }
        public string dm_name { get; set; }
        public string dm_Address1 { get; set; }
        public string dm_Address2 { get; set; }
        public string dm_City { get; set; }
        public Nullable<System.DateTime> dm_ClosedDate { get; set; }
        public string dm_Number { get; set; }
        public string dm_Phone { get; set; }
        public Nullable<bool> dm_PrimaryReportingEntity { get; set; }
        public string dm_State { get; set; }
        public string dm_TaxID { get; set; }
        public string dm_Zip { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_DueFromAccount { get; set; }
        public Nullable<System.Guid> dm_DueToAccount { get; set; }
        public Nullable<bool> dm_Inactive { get; set; }
        public Nullable<System.Guid> dm_defaultCheckingAccount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string StateId { get; set; }
    }
}
