//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_laborextensionbase
    {
        public System.Guid dm_laborId { get; set; }
        public string dm_Labor { get; set; }
        public string dm_DateText { get; set; }
        public Nullable<System.DateTime> dm_DateWorked { get; set; }
        public Nullable<System.DateTime> dm_EndTime { get; set; }
        public Nullable<decimal> dm_Hours { get; set; }
        public Nullable<decimal> dm_PayRate { get; set; }
        public Nullable<decimal> dm_payrate_Base { get; set; }
        public Nullable<int> dm_PayrollStatus { get; set; }
        public Nullable<System.DateTime> dm_StartTime { get; set; }
        public Nullable<decimal> dm_Total { get; set; }
        public Nullable<decimal> dm_total_Base { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_DailySalesSummary { get; set; }
        public Nullable<System.Guid> dm_Employee { get; set; }
        public Nullable<System.Guid> dm_EmployeeJobTitle { get; set; }
        public Nullable<System.Guid> dm_JobTitle { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_PayCode { get; set; }
        public Nullable<System.Guid> dm_CateringEvent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
