//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_menuItemextensionbase
    {
        public System.Guid dm_menuitemId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_COGSCategory { get; set; }
        public Nullable<bool> dm_Entree { get; set; }
        public Nullable<decimal> dm_EstimatedCost { get; set; }
        public Nullable<decimal> dm_estimatedcost_Base { get; set; }
        public Nullable<decimal> dm_Price { get; set; }
        public Nullable<decimal> dm_price_Base { get; set; }
        public Nullable<decimal> dm_TargetMargin { get; set; }
        public Nullable<System.Guid> dm_Recipe { get; set; }
        public Nullable<System.Guid> dm_MenuItemCategory1 { get; set; }
        public Nullable<System.Guid> dm_MenuItemCategory2 { get; set; }
        public Nullable<System.Guid> dm_MenuItemCategory3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
