//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_preferencesextensionbase
    {
        public System.Guid dm_preferencesId { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_AccountingActive { get; set; }
        public Nullable<int> dm_AccountLookup { get; set; }
        public Nullable<bool> dm_Attribute1Inactive { get; set; }
        public string dm_Attribute1Name { get; set; }
        public Nullable<bool> dm_Attribute1Required { get; set; }
        public Nullable<bool> dm_Attribute2Inactive { get; set; }
        public string dm_Attribute2Name { get; set; }
        public Nullable<bool> dm_Attribute2Required { get; set; }
        public Nullable<int> dm_AttributeHierarchy { get; set; }
        public Nullable<bool> dm_CateringActive { get; set; }
        public Nullable<bool> dm_CateringSalesEnteredinPOS { get; set; }
        public string dm_CRMOrgName { get; set; }
        public Nullable<bool> dm_EditPaidoutComments { get; set; }
        public Nullable<bool> dm_FranchisingActive { get; set; }
        public Nullable<bool> dm_HouseAccountPaymentsinPOS { get; set; }
        public Nullable<bool> dm_ItemCosting { get; set; }
        public Nullable<bool> dm_MarketingActive { get; set; }
        public Nullable<bool> dm_OperationsActive { get; set; }
        public Nullable<int> dm_PaymentTypeSeparation { get; set; }
        public Nullable<int> dm_PLReportPercentOf { get; set; }
        public Nullable<int> dm_PrintAs { get; set; }
        public Nullable<int> dm_SalesAnalysis { get; set; }
        public Nullable<int> dm_SalesandLaborAnalysisTimeIncrement { get; set; }
        public Nullable<decimal> dm_SalesTaxRate { get; set; }
        public Nullable<System.Guid> dm_AccountsPayable { get; set; }
        public Nullable<System.Guid> dm_AccountsReceivable { get; set; }
        public Nullable<System.Guid> dm_CateringAdditionalRevenue { get; set; }
        public Nullable<System.Guid> dm_CateringDepositAccount { get; set; }
        public Nullable<System.Guid> dm_Checking { get; set; }
        public Nullable<System.Guid> dm_CreditExpected { get; set; }
        public Nullable<System.Guid> dm_DSSRoundingAdjustment { get; set; }
        public Nullable<System.Guid> dm_FoodSales { get; set; }
        public Nullable<System.Guid> dm_RetainedEarnings { get; set; }
        public Nullable<System.Guid> dm_SalesTax { get; set; }
        public Nullable<System.Guid> dm_UndepositedFunds { get; set; }
        public Nullable<System.Guid> dm_APPassthroughItem { get; set; }
        public Nullable<System.Guid> dm_DiscountItem { get; set; }
        public Nullable<System.Guid> dm_HouseAccountItem { get; set; }
        public string dm_AppPath { get; set; }
        public string dm_ReportPath { get; set; }
        public Nullable<bool> dm_ChartsActive { get; set; }
        public Nullable<bool> dm_POSOverwriteEmployeeInfo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> dm_Theme { get; set; }
        public string dm_Pop3User { get; set; }
        public string dm_Pop3Password { get; set; }
        public string dm_Pop3Server { get; set; }
        public string dm_Pop3Port { get; set; }
        public Nullable<bool> dm_Pop3SSL { get; set; }
        public string accesskey { get; set; }
        public string secretkey { get; set; }
        public string bucketname { get; set; }
        public Nullable<bool> dm_SchedulingActive { get; set; }
        public Nullable<int> dm_PayrollClearingType { get; set; }
        public string Category1Value { get; set; }
        public Nullable<bool> Category1Inactive { get; set; }
        public string Category2Value { get; set; }
        public Nullable<bool> Category2Inactive { get; set; }
        public string Category3Value { get; set; }
        public Nullable<bool> Category3Inactive { get; set; }
        public string Category4Value { get; set; }
        public Nullable<bool> Category4Inactive { get; set; }
        public string Category5Value { get; set; }
        public Nullable<bool> Category5Inactive { get; set; }
        public string Category6Value { get; set; }
        public Nullable<bool> Category6Inactive { get; set; }
        public string Category7Value { get; set; }
        public Nullable<bool> Category7Inactive { get; set; }
        public string Category8Value { get; set; }
        public Nullable<bool> Category8Inactive { get; set; }
        public string Category9Value { get; set; }
        public Nullable<bool> Category9Inactive { get; set; }
        public string Category10Value { get; set; }
        public Nullable<bool> Category10Inactive { get; set; }
        public Nullable<int> LocationLookup { get; set; }
        public Nullable<bool> CommissaryActive { get; set; }
        public Nullable<int> SalesAccountSeparation { get; set; }
        public Nullable<bool> dm_RenovoActive { get; set; }
        public Nullable<System.DateTime> MaintenanceStartDate { get; set; }
        public Nullable<System.DateTime> MaintenanceEndDate { get; set; }
        public string MaintenanceNote { get; set; }
        public Nullable<bool> dm_SpecialPayActive { get; set; }
        public Nullable<int> EmployeeFullName { get; set; }
        public Nullable<bool> POSTrackPaidoutTypes { get; set; }
        public Nullable<int> duplicateInvoiceNumber { get; set; }
        public Nullable<bool> DiscountCombinedInJE { get; set; }
        public string LocationAdditionalInfoNumber1 { get; set; }
        public string LocationAdditionalInfoNumber2 { get; set; }
        public string LocationAdditionalInfoNumber3 { get; set; }
        public string LocationAdditionalInfoText1 { get; set; }
        public string LocationAdditionalInfoText2 { get; set; }
        public Nullable<int> DuplicateInvoiceAmount { get; set; }
    }
}
