//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_paymentTypeAccountextensionbase
    {
        public System.Guid dm_paymenttypeaccountId { get; set; }
        public string dm_paymenttype { get; set; }
        public Nullable<bool> dm_ConsolidateOnFlash { get; set; }
        public string dm_CreditCardGroup { get; set; }
        public string dm_ExceptionComment { get; set; }
        public Nullable<bool> dm_ExcludeDiscount { get; set; }
        public Nullable<int> dm_PaymentGroup { get; set; }
        public Nullable<bool> dm_ThisisanExceptionType { get; set; }
        public Nullable<System.Guid> dm_Company { get; set; }
        public Nullable<System.Guid> dm_GLAccount { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
