//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_salesDetailextensionbase
    {
        public System.Guid dm_salesdetailId { get; set; }
        public string dm_menuitem { get; set; }
        public Nullable<decimal> dm_Amount { get; set; }
        public string dm_CustomerPOSText { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public Nullable<decimal> dm_Quantity { get; set; }
        public Nullable<bool> dm_Void { get; set; }
        public Nullable<System.Guid> dm_Company { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_Sale { get; set; }
        public Nullable<System.Guid> dm_SalesAccount { get; set; }
        public Nullable<System.Guid> dm_Category { get; set; }
        public Nullable<System.Guid> dm_houseaccounttransaction { get; set; }
        public Nullable<System.Guid> dm_TransactionDetailId { get; set; }
        public Nullable<System.Guid> dm_CateringEvent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public int Rowid { get; set; }
    }
}
