//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_sales
    {
        public System.Guid dm_salesId { get; set; }
        public string dm_receiptnumber { get; set; }
        public string dm_checknumber { get; set; }
        public string dm_Comment { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_DateText { get; set; }
        public Nullable<int> dm_dayofweek { get; set; }
        public string dm_DayPart { get; set; }
        public Nullable<int> dm_DayPartNumber { get; set; }
        public Nullable<decimal> dm_NetSales { get; set; }
        public Nullable<int> dm_NumberofGuests { get; set; }
        public Nullable<int> dm_OrderHour { get; set; }
        public Nullable<decimal> dm_SalesAmount { get; set; }
        public Nullable<decimal> dm_TaxAmount { get; set; }
        public string dm_Time { get; set; }
        public Nullable<decimal> dm_TipAmount { get; set; }
        public Nullable<decimal> dm_TotalAmount { get; set; }
        public Nullable<decimal> dm_TotalPayment { get; set; }
        public Nullable<bool> dm_Unbalanced { get; set; }
        public bool dm_Void { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_DailySalesSummary { get; set; }
        public Nullable<System.Guid> dm_Server { get; set; }
        public Nullable<System.Guid> dm_FiscalDate { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_ServiceType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public int Rowid { get; set; }
    }
}
