//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_salesAccountextensionbase
    {
        public System.Guid dm_salesaccountId { get; set; }
        public string dm_name { get; set; }
        public Nullable<int> dm_SalesAccountType { get; set; }
        public Nullable<System.Guid> dm_GLAccount { get; set; }
        public Nullable<System.Guid> dm_Category { get; set; }
        public Nullable<System.Guid> dm_ServiceType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
