//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_transaction
    {
        public System.Guid dm_transactionId { get; set; }
        public string dm_name { get; set; }
        public string dm_0 { get; set; }
        public string dm_1 { get; set; }
        public string dm_10 { get; set; }
        public Nullable<decimal> dm_1099Amount { get; set; }
        public Nullable<decimal> dm_1099amount_Base { get; set; }
        public string dm_1099AmountCalc { get; set; }
        public Nullable<int> dm_1099Box { get; set; }
        public Nullable<bool> dm_1099Vendor { get; set; }
        public string dm_11 { get; set; }
        public string dm_12 { get; set; }
        public string dm_13 { get; set; }
        public string dm_14 { get; set; }
        public string dm_2 { get; set; }
        public string dm_3 { get; set; }
        public string dm_4 { get; set; }
        public string dm_5 { get; set; }
        public string dm_6 { get; set; }
        public string dm_7 { get; set; }
        public string dm_8 { get; set; }
        public string dm_AccountingSystemID { get; set; }
        public Nullable<int> dm_Action { get; set; }
        public string dm_ActionData { get; set; }
        public string dm_Address1 { get; set; }
        public string dm_Address2 { get; set; }
        public string dm_AddressBox { get; set; }
        public Nullable<decimal> dm_Amount { get; set; }
        public Nullable<decimal> dm_amount_Base { get; set; }
        public string dm_amountcalc { get; set; }
        public Nullable<decimal> dm_AmountRemaining { get; set; }
        public Nullable<decimal> dm_amountremaining_Base { get; set; }
        public string dm_AmountText { get; set; }
        public Nullable<decimal> dm_AppliedAmount { get; set; }
        public Nullable<decimal> dm_appliedamount_Base { get; set; }
        public Nullable<decimal> dm_Apply1Amount { get; set; }
        public Nullable<decimal> dm_apply1amount_Base { get; set; }
        public Nullable<System.DateTime> dm_Apply1Date { get; set; }
        public Nullable<int> dm_ApprovalStatus { get; set; }
        public Nullable<System.DateTime> dm_ApprovedOn { get; set; }
        public Nullable<bool> dm_BeginningBalance { get; set; }
        public string dm_blank { get; set; }
        public Nullable<bool> dm_BrandNew { get; set; }
        public string dm_BudgetGroup { get; set; }
        public Nullable<int> dm_BudgetYear { get; set; }
        public Nullable<bool> dm_CanUnapprove { get; set; }
        public string dm_ChangeAddressButton { get; set; }
        public string dm_CheckRun { get; set; }
        public Nullable<decimal> dm_CheckRunAmount { get; set; }
        public Nullable<decimal> dm_checkrunamount_Base { get; set; }
        public Nullable<decimal> dm_CheckRunDiscountAmount { get; set; }
        public Nullable<decimal> dm_checkrundiscountamount_Base { get; set; }
        public string dm_City { get; set; }
        public string dm_Comment { get; set; }
        public string dm_CompanyText { get; set; }
        public Nullable<bool> dm_CountComplete { get; set; }
        public string dm_Country { get; set; }
        public Nullable<System.DateTime> dm_CountTime { get; set; }
        public string dm_CreditComment { get; set; }
        public Nullable<decimal> dm_CreditExpected { get; set; }
        public Nullable<decimal> dm_creditexpected_Base { get; set; }
        public string dm_CreditExpectedCalc { get; set; }
        public Nullable<decimal> dm_CreditExpectedHeader { get; set; }
        public Nullable<decimal> dm_creditexpectedheader_Base { get; set; }
        public Nullable<decimal> dm_CreditTotal { get; set; }
        public Nullable<decimal> dm_credittotal_Base { get; set; }
        public Nullable<System.DateTime> dm_Date { get; set; }
        public string dm_DateText { get; set; }
        public Nullable<decimal> dm_DebitTotal { get; set; }
        public Nullable<decimal> dm_debittotal_Base { get; set; }
        public Nullable<bool> dm_DefaultBudget { get; set; }
        public Nullable<bool> dm_DepositNow { get; set; }
        public string dm_DetailInsert { get; set; }
        public Nullable<decimal> dm_DetailsTotal { get; set; }
        public Nullable<decimal> dm_detailstotal_Base { get; set; }
        public Nullable<decimal> dm_DiscountAmount { get; set; }
        public Nullable<System.DateTime> dm_DiscountDate { get; set; }
        public Nullable<System.DateTime> dm_DueDate { get; set; }
        public Nullable<bool> dm_ExcludeFrom1099 { get; set; }
        public Nullable<decimal> dm_FirstAmount { get; set; }
        public Nullable<decimal> dm_firstamount_Base { get; set; }
        public Nullable<bool> dm_Franchising { get; set; }
        public string dm_Frequency { get; set; }
        public Nullable<bool> dm_IndividualDeposit { get; set; }
        public Nullable<bool> dm_InUse { get; set; }
        public Nullable<System.DateTime> dm_LastCountDate { get; set; }
        public Nullable<int> dm_LegalEntityAttribute { get; set; }
        public Nullable<int> dm_LocationAttribute { get; set; }
        public Nullable<bool> dm_MostRecent { get; set; }
        public string dm_NoUnapproveReason { get; set; }
        public string dm_Number { get; set; }
        public Nullable<bool> dm_Only1Detail { get; set; }
        public Nullable<int> dm_PaymentMethod { get; set; }
        public Nullable<System.DateTime> dm_PayrollEndDate { get; set; }
        public Nullable<System.DateTime> dm_PayrollStartDate { get; set; }
        public Nullable<int> dm_PrintStatus { get; set; }
        public Nullable<bool> dm_Rapid { get; set; }
        public Nullable<bool> dm_Reconciled { get; set; }
        public string dm_ReportParameters { get; set; }
        public Nullable<int> dm_SaveType { get; set; }
        public Nullable<bool> dm_ShortPay { get; set; }
        public Nullable<int> dm_Source { get; set; }
        public string dm_State { get; set; }
        public Nullable<decimal> dm_TaxableAmount { get; set; }
        public Nullable<decimal> dm_taxableamount_Base { get; set; }
        public Nullable<decimal> dm_TaxableSubtotal { get; set; }
        public Nullable<decimal> dm_taxablesubtotal_Base { get; set; }
        public Nullable<decimal> dm_TaxAmount { get; set; }
        public Nullable<decimal> dm_taxamount_Base { get; set; }
        public Nullable<decimal> dm_TaxPercent { get; set; }
        public Nullable<bool> dm_Template { get; set; }
        public Nullable<int> dm_TransactionType { get; set; }
        public Nullable<System.DateTime> dm_TransferToReconcileDate { get; set; }
        public Nullable<decimal> dm_UnassignedAmount { get; set; }
        public Nullable<decimal> dm_unassignedamount_Base { get; set; }
        public Nullable<bool> dm_Voided { get; set; }
        public Nullable<bool> dm_Voiding { get; set; }
        public string dm_Zip { get; set; }
        public Nullable<System.Guid> dm_Company { get; set; }
        public Nullable<System.Guid> dm_Attribute1 { get; set; }
        public Nullable<System.Guid> dm_Attribute2 { get; set; }
        public Nullable<System.Guid> dm_BankReconciliation { get; set; }
        public Nullable<System.Guid> dm_TransferToBankReconciliation { get; set; }
        public Nullable<System.Guid> dm_DailySalesSummary { get; set; }
        public Nullable<System.Guid> dm_R365DailySalesSummary { get; set; }
        public Nullable<System.Guid> dm_CheckingAccount { get; set; }
        public Nullable<System.Guid> dm_CheckRunDiscountAccount { get; set; }
        public Nullable<System.Guid> dm_FirstAccount { get; set; }
        public Nullable<System.Guid> dm_OffsetAccount { get; set; }
        public Nullable<System.Guid> dm_TaxAccount { get; set; }
        public Nullable<System.Guid> dm_TransferTo { get; set; }
        public Nullable<System.Guid> dm_LegalEntity { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<System.Guid> dm_ToLocation { get; set; }
        public Nullable<System.Guid> dm_PaymentTerms { get; set; }
        public Nullable<System.Guid> dm_Apply1Transaction { get; set; }
        public Nullable<System.Guid> dm_BudgetMaster { get; set; }
        public Nullable<System.Guid> dm_Deposit { get; set; }
        public Nullable<System.Guid> dm_LastStockCount { get; set; }
        public Nullable<System.Guid> dm_TemplateTransaction { get; set; }
        public Nullable<System.Guid> dm_CateringEvent { get; set; }
        public Nullable<System.Guid> dm_ApprovedBy { get; set; }
        public Nullable<int> dm_AutoRecurrence { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> dm_DaysInAdvance { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<System.Guid> CommissaryFulfillment { get; set; }
        public Nullable<int> CutoffReminderSent { get; set; }
        public Nullable<System.Guid> PaymentExpected { get; set; }
        public Nullable<System.Guid> Budget { get; set; }
        public Nullable<int> SpreadType { get; set; }
        public Nullable<System.Guid> SpreadLink { get; set; }
        public Nullable<int> TimesToRepeat { get; set; }
        public Nullable<int> TimesRepeated { get; set; }
        public Nullable<int> ScheduleStatus { get; set; }
        public Nullable<System.Guid> SpreadAccount { get; set; }
        public Nullable<System.DateTime> FirstSpreadDate { get; set; }
        public Nullable<System.DateTime> LastSpreadDate { get; set; }
        public Nullable<int> MobileQty { get; set; }
    }
}
