//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_unitOfMeasureextensionbase
    {
        public System.Guid dm_unitofmeasureId { get; set; }
        public string dm_name { get; set; }
        public Nullable<bool> dm_Auto { get; set; }
        public Nullable<bool> dm_Base { get; set; }
        public Nullable<decimal> dm_BaseQty { get; set; }
        public Nullable<int> dm_Category { get; set; }
        public string dm_Container { get; set; }
        public Nullable<decimal> dm_EquivalentQty { get; set; }
        public Nullable<int> dm_MeasureType { get; set; }
        public string dm_PacksizeDescription { get; set; }
        public Nullable<bool> dm_Purchase { get; set; }
        public Nullable<System.Guid> dm_BaseUofM { get; set; }
        public Nullable<System.Guid> dm_EquivalentUofM { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
