//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_UserActivityextensionbase
    {
        public System.Guid userActivityId { get; set; }
        public string dbName { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public string Page { get; set; }
        public string pageId { get; set; }
        public string action { get; set; }
        public string importTypes { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
