//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_VendorItemextensionbase
    {
        public System.Guid dm_vendoritemId { get; set; }
        public string dm_name { get; set; }
        public Nullable<decimal> dm_AcceptableVariancePercent { get; set; }
        public Nullable<System.DateTime> dm_ContractExpiration { get; set; }
        public Nullable<decimal> dm_ContractPrice { get; set; }
        public Nullable<decimal> dm_contractprice_Base { get; set; }
        public Nullable<decimal> dm_SplitContractPrice { get; set; }
        public Nullable<decimal> dm_splitcontractprice_Base { get; set; }
        public string dm_VendorItemName { get; set; }
        public string dm_VendorItemNumber { get; set; }
        public Nullable<System.Guid> dm_vendor { get; set; }
        public Nullable<System.Guid> dm_Item { get; set; }
        public Nullable<System.Guid> dm_PurchasingUofM { get; set; }
        public Nullable<System.Guid> dm_SplitUofM { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
