//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Batch { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<bool> allowingtextmessaging { get; set; }
        public string city { get; set; }
        public string employeeId { get; set; }
        public string firstname { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string imageattachmentid { get; set; }
        public string lastname { get; set; }
        public string Middlename { get; set; }
        public string mobilephone { get; set; }
        public string payrollid { get; set; }
        public string posid { get; set; }
        public string primarylocation { get; set; }
        public string ssnumber { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string employeelink { get; set; }
        public int Id { get; set; }
    }
}
