//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJobTitle
    {
        public string Batch { get; set; }
        public string Location { get; set; }
        public string EmployeePOSId { get; set; }
        public string JobTitlePOSId { get; set; }
        public string EmpJobPOSId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> DateReceivedPosition { get; set; }
        public int Id { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
