//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> dm_ForecastDate { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public Nullable<int> dm_Value { get; set; }
        public Nullable<decimal> dm_Amount { get; set; }
    }
}
