//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMapping
    {
        public string DisplayName { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public string Datatype { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ColumnName { get; set; }
        public string LookUpColumn { get; set; }
        public string LinkedColumn { get; set; }
        public string Template { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> ImportType { get; set; }
        public int Id { get; set; }
    }
}
