//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        public int ImportID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<int> IntegrationStatus { get; set; }
        public Nullable<int> IntegrationType { get; set; }
        public string IntegrationSource { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public string IntegrationMessage { get; set; }
        public string AttachmentLink { get; set; }
        public string LinkToTransaction { get; set; }
    }
}
