//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportType
    {
        public string ID { get; set; }
        public string TableName { get; set; }
        public string BaseTable { get; set; }
        public string ExtensionTable { get; set; }
        public string NameField { get; set; }
        public string IdField { get; set; }
        public string SqlProc { get; set; }
    }
}
