//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMultiplier
    {
        public System.Guid dm_itemid { get; set; }
        public string dm_name { get; set; }
        public System.Guid src { get; set; }
        public string srcName { get; set; }
        public System.Guid dst { get; set; }
        public string dstName { get; set; }
        public Nullable<decimal> costMultiplier { get; set; }
        public Nullable<decimal> qtyMultiplier { get; set; }
    }
}
