//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTitle
    {
        public string Batch { get; set; }
        public string Description { get; set; }
        public string Glaccount { get; set; }
        public string JobCode { get; set; }
        public string JobTitle1 { get; set; }
        public string JobTitleID { get; set; }
        public string Location { get; set; }
        public string PayRate { get; set; }
        public string POSID { get; set; }
        public int Id { get; set; }
    }
}
