//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class R365_RFYI_ORG
    {
        public string Location_No { get; set; }
        public string LocationName { get; set; }
        public System.Guid LocationID { get; set; }
        public string LegalEntityNumber { get; set; }
        public string LegalEntityName { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public string Attribute1Number { get; set; }
        public string Attribute1Name { get; set; }
        public Nullable<System.Guid> Attribute1ID { get; set; }
        public string Attribute2Number { get; set; }
        public string Attribute2Name { get; set; }
        public Nullable<System.Guid> Attribute2ID { get; set; }
        public Nullable<System.DateTime> LocationModifiedOn { get; set; }
    }
}
