//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class R365ReportTrxDetailA
    {
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Location_No { get; set; }
        public string LocationName { get; set; }
        public string LegalEntityNumber { get; set; }
        public string LegalEntityName { get; set; }
        public string Attribute1Number { get; set; }
        public string Attribute1Name { get; set; }
        public string Attribute2Number { get; set; }
        public string Attribute2Name { get; set; }
        public System.Guid GLAccountID { get; set; }
        public string GLAccountName { get; set; }
        public string GLAccountNumber { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid TrxIDGuid { get; set; }
        public string TrxDetailIDGuid { get; set; }
        public int LineItem { get; set; }
        public string TrxNumber { get; set; }
        public string TrxName { get; set; }
        public string BudgetActual { get; set; }
        public Nullable<System.Guid> BudgetID { get; set; }
    }
}
