//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipePortionCost
    {
        public System.Guid dm_itemid { get; set; }
        public string dm_name { get; set; }
        public Nullable<decimal> dm_cost { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostPerPortion { get; set; }
        public Nullable<bool> dm_availableininventory { get; set; }
        public Nullable<decimal> dm_portionsize { get; set; }
    }
}
