//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public System.Guid RoleId { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public Nullable<bool> PrimaryRole { get; set; }
        public string Description { get; set; }
    }
}
