//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public string Batch { get; set; }
        public string MenuItem { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<bool> Void { get; set; }
        public string SalesID { get; set; }
        public string Category { get; set; }
        public string Company { get; set; }
        public string CustomerPOSText { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public int Id { get; set; }
    }
}
