//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedView
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string List { get; set; }
        public string Name { get; set; }
        public string DatasourceText { get; set; }
        public string GridText { get; set; }
        public Nullable<bool> DefaultView { get; set; }
        public Nullable<bool> SystemView { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
