//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedMapping
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string TableName { get; set; }
        public string displayName { get; set; }
        public string mappedValue { get; set; }
        public string TemplateName { get; set; }
    }
}
