//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEvent
    {
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.Guid> Location { get; set; }
        public Nullable<System.Guid> Job { get; set; }
        public Nullable<System.Guid> Responsibility { get; set; }
        public Nullable<System.Guid> Employee { get; set; }
        public Nullable<System.Guid> Schedule { get; set; }
        public Nullable<int> JobRating { get; set; }
        public Nullable<System.Guid> Site { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<int> Request { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public string RequestComment { get; set; }
        public Nullable<System.Guid> TradeShift { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid ScheduleEventId { get; set; }
        public string ManagerComment { get; set; }
        public Nullable<System.Guid> CateringEvent { get; set; }
    }
}
