//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupStep
    {
        public System.Guid StepID { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public Nullable<System.Guid> Section { get; set; }
        public string Name { get; set; }
        public string HeadLine { get; set; }
        public Nullable<System.Guid> DependentOn { get; set; }
        public Nullable<bool> StepRequired { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.Guid> UserCompleted { get; set; }
        public string AdditionalInfo { get; set; }
        public string TemplateURL { get; set; }
        public string AppPath { get; set; }
    }
}
