//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupSection
    {
        public System.Guid SectionID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public Nullable<System.Guid> Feature { get; set; }
        public string AppPath { get; set; }
    }
}
