//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserBase
    {
        public System.Guid SystemUserId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> BusinessUnitId { get; set; }
        public Nullable<System.Guid> ParentSystemUserId { get; set; }
        public string FirstName { get; set; }
        public string Salutation { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PersonalEMailAddress { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string Title { get; set; }
        public string InternalEMailAddress { get; set; }
        public string JobTitle { get; set; }
        public string MobileAlertEMail { get; set; }
        public Nullable<int> PreferredEmailCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> PreferredPhoneCode { get; set; }
        public Nullable<int> PreferredAddressCode { get; set; }
        public string PhotoUrl { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> PassportLo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> PassportHi { get; set; }
        public string DisabledReason { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string GovernmentId { get; set; }
        public byte[] VersionNumber { get; set; }
        public string Skills { get; set; }
        public Nullable<bool> DisplayInServiceViews { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<System.Guid> ActiveDirectoryGuid { get; set; }
        public Nullable<bool> SetupUser { get; set; }
        public Nullable<System.Guid> SiteId { get; set; }
        public string WindowsLiveID { get; set; }
        public Nullable<int> IncomingEmailDeliveryMethod { get; set; }
        public Nullable<int> OutgoingEmailDeliveryMethod { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<int> AccessMode { get; set; }
        public Nullable<int> InviteStatusCode { get; set; }
        public Nullable<bool> IsActiveDirectoryUser { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public string YomiFullName { get; set; }
        public string YomiLastName { get; set; }
        public string YomiMiddleName { get; set; }
        public string YomiFirstName { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<bool> IsIntegrationUser { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<int> EmailRouterAccessApproval { get; set; }
        public Nullable<bool> DefaultFiltersPopulated { get; set; }
        public Nullable<int> CALType { get; set; }
        public Nullable<System.Guid> QueueId { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<bool> IsSyncWithDirectory { get; set; }
        public Nullable<bool> IsLicensed { get; set; }
        public string dm_EmailPassword { get; set; }
        public string dm_EmailOutGoingMailServer { get; set; }
        public string dm_EmailPort { get; set; }
        public Nullable<bool> dm_EmailSSL { get; set; }
        public string dm_Login { get; set; }
        public string dm_LoginPassword { get; set; }
        public Nullable<bool> dm_ChangePassword { get; set; }
        public Nullable<bool> dm_AvailableToAllLocations { get; set; }
        public Nullable<bool> dm_Inactive { get; set; }
        public Nullable<bool> dm_R365 { get; set; }
        public Nullable<System.Guid> dm_Location { get; set; }
        public string defaultPage { get; set; }
        public string DefaultDashboard { get; set; }
        public Nullable<int> dm_AllReports { get; set; }
        public Nullable<bool> dm_NewFeature { get; set; }
        public Nullable<int> dm_Theme { get; set; }
        public Nullable<int> R365Manager { get; set; }
        public Nullable<bool> FullAccess { get; set; }
    }
}
