//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemUserAndEmployee
    {
        public string username { get; set; }
        public int dm_R365 { get; set; }
        public System.Guid userId { get; set; }
        public string pw { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> dm_changePassword { get; set; }
        public string defaultPage { get; set; }
        public int LoginType { get; set; }
        public Nullable<int> AvailableToAllLocations { get; set; }
        public Nullable<int> dm_Newfeature { get; set; }
        public Nullable<System.Guid> defaultLocation { get; set; }
        public int R365Manager { get; set; }
        public int AppAccess { get; set; }
        public int FullAccess { get; set; }
    }
}
