//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int ThemeId { get; set; }
        public string ThemeName { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Settings { get; set; }
        public Nullable<bool> IsR365 { get; set; }
    }
}
