//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetailAuditLog
    {
        public string TransactionID { get; set; }
        public System.Guid TransactionDetailID { get; set; }
        public string AccountingSystemID { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string Comment { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> DetailSort { get; set; }
        public Nullable<int> DetailType { get; set; }
        public Nullable<decimal> EachAmount { get; set; }
        public Nullable<bool> Exclude { get; set; }
        public string GLAccount { get; set; }
        public string IntercompanyCreditAccount { get; set; }
        public string IntercompanyCreditLocation { get; set; }
        public string IntercompanyDebitAccount { get; set; }
        public string IntercompanyDebitLocation { get; set; }
        public string Item { get; set; }
        public string Location { get; set; }
        public Nullable<int> MissingReceipt { get; set; }
        public string OffsetAccount { get; set; }
        public Nullable<decimal> PreviousCountTotal { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> R365Category { get; set; }
        public string R365Job { get; set; }
        public string R365PaymentTypeAccount { get; set; }
        public string R365SalesAccount { get; set; }
        public string R365SalesPayment { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<decimal> StorageLocationSort { get; set; }
        public Nullable<int> Taxable { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string TransactionApply { get; set; }
        public string TransactionLocation { get; set; }
        public string UndepositedFundDetail { get; set; }
        public string UnitOfMeasure { get; set; }
        public string VendorItemNumber { get; set; }
        public int ID { get; set; }
    }
}
