//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAuditLog
    {
        public string Action { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid TransactionID { get; set; }
        public Nullable<decimal> Amount1099 { get; set; }
        public Nullable<int> Box1099 { get; set; }
        public string AccountingSystemID { get; set; }
        public string ActionData { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressBox { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountRemaining { get; set; }
        public string AmountText { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> BeginningBalance { get; set; }
        public Nullable<int> BudgetYear { get; set; }
        public string CateringEvent { get; set; }
        public string CheckingAccount { get; set; }
        public string CheckRun { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public string Company { get; set; }
        public string CompanyText { get; set; }
        public Nullable<System.DateTime> CountTime { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountComplete { get; set; }
        public string CreditComment { get; set; }
        public Nullable<decimal> CreditExpected { get; set; }
        public Nullable<decimal> CreditTotal { get; set; }
        public string DailySalesSummary { get; set; }
        public string DateText { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<decimal> DebitTotal { get; set; }
        public Nullable<int> DepositNow { get; set; }
        public Nullable<decimal> DetailsTotal { get; set; }
        public Nullable<System.DateTime> DiscountDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string FirstAccount { get; set; }
        public Nullable<decimal> FirstAmount { get; set; }
        public Nullable<int> Franchising { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> IndividualDeposit { get; set; }
        public Nullable<int> InUse { get; set; }
        public Nullable<System.DateTime> LastCountDate { get; set; }
        public string LastStockCount { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<int> Only1Detail { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<System.DateTime> PayrollStartDate { get; set; }
        public Nullable<System.DateTime> PayrollEndDate { get; set; }
        public string R365DailySalesSummary { get; set; }
        public string ReportParameters { get; set; }
        public Nullable<int> ShortPay { get; set; }
        public Nullable<int> SourceTransaction { get; set; }
        public string StateAddress { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> TaxableSubtotal { get; set; }
        public string TaxAccount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<int> Template { get; set; }
        public string TemplateTransaction { get; set; }
        public string ToLocation { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string TransferTo { get; set; }
        public Nullable<int> Voided { get; set; }
        public Nullable<int> Voiding { get; set; }
        public string Zip { get; set; }
        public int ID { get; set; }
    }
}
