//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Batch { get; set; }
        public Nullable<int> NumberOfDetails { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Number { get; set; }
        public string R365Id { get; set; }
        public string Vendor { get; set; }
        public string Date { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string R365TransactionId { get; set; }
        public string POSTransactionId { get; set; }
        public string VendorNumber { get; set; }
        public int Id { get; set; }
    }
}
