//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERSION
    {
        public int ID { get; set; }
        public string SERVER { get; set; }
        public string DATABASE { get; set; }
        public string USER { get; set; }
        public string OBJECT { get; set; }
        public string ACTION { get; set; }
        public System.DateTime DATE { get; set; }
        public string CODE { get; set; }
    }
}
