//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataResturantsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUser
    {
        public System.Guid UserId { get; set; }
        public string LOGIN { get; set; }
        public string Password { get; set; }
        public int LoginType { get; set; }
        public Nullable<int> AvailableToAllLocations { get; set; }
    }
}
